# Generated by Django 2.0.5 on 2018-05-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication_link',
            name='name',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Name'),
        ),
    ]
