# Generated by Django 2.0.5 on 2018-06-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180506_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_member',
            name='position',
            field=models.IntegerField(null=True, unique=True, verbose_name='Position'),
        ),
    ]
