# Generated by Django 2.0.4 on 2019-09-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_lab_member_trainees'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Title')),
                ('post_date', models.DateField(auto_now_add=True, verbose_name='Posting Date')),
                ('jobid', models.IntegerField(verbose_name='Job ID#')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Job Listing',
            },
        ),
    ]
