# Generated by Django 2.0.4 on 2020-09-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_job_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_listing',
            name='jobid',
        ),
    ]
